### ISSUE TITLE
What is the use case of this mod?

### ISSUE THREAD

**Issue by SpecialtyK** [noobanidus/threadsafety#1]
I didn't see a place to comment so I am leaving it here. What exactly does being thread safe do? Is this mod for use with a specific mod in mind, for mainly vanilla/few mods, or useful/compatible in a heavily modded environment like a general bugfixing/stability mod? For reference I am using a large custom modpack on 16.5 forge with many world generation and performance enhancing mods. Thank you for your time.

**Comment by noobanidus** [comment]
It's specifically for when you get crashes during world generation that are related to the StructureManager, TemplateManager or WeightedBlockStateProvider.

Due to asynchronous world generation, it's possible that using features (especially those that use WeightedBlockStateProvider) in both the overworld and in dimensions can cause a "concurrent modification" crash.

You should only need this if you're actually getting crashes; additionally, I think several other mods, including Repurposed Structures (not 100% sure on that) also implement this, so only add it if you need to.

**Comment by SpecialtyK** [comment]
I see, thank you for clarification.
